module CamMessages
{
  #pragma DCPS_DATA_TYPE "CamMessages::Message"
  #pragma DCPS_DATA_KEY "CamMessages::Message subject_id"

  struct CamTestMessage
  {
    string from;
    string subject;
    long subject_id;
    string text;
    long count;
  };
};
